version: '3.8'
services:
  app:
    build: ./backend
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    image: backend:backend
    container_name: django-backend
    command:  sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    restart: on-failure
    ports:
      - 3000:3000
    container_name: react-frontend
    command: npm start
