# Generated by Django 4.2.9 on 2024-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=2000)),
                ("dateTimeCreated", models.DateTimeField()),
                ("scheaduleDateTime", models.DateTimeField()),
                ("taskDone", models.BooleanField()),
                (
                    "taskPriority",
                    models.IntegerField(
                        choices=[(0, "Low"), (1, "Normal"), (2, "High")]
                    ),
                ),
            ],
        ),
    ]
