# Generated by Django 4.2.9 on 2024-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="taskDescription",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="todo",
            name="task",
            field=models.CharField(max_length=200),
        ),
    ]
