# Generated by Django 4.2.9 on 2024-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_todo_taskdescription_alter_todo_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="taskDone",
            field=models.BooleanField(default=False),
        ),
    ]
