# Generated by Django 4.2.9 on 2024-02-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_todo_taskdone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="taskPriority",
            field=models.IntegerField(choices=[(1, "Low"), (2, "Normal"), (3, "High")]),
        ),
    ]
