# Generated by Django 4.2.9 on 2024-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_alter_todo_taskpriority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="taskDescription",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
    ]
